INFO     root:tasks.py:25 Reencryption ac92834c-b6ea-4f94-a77e-f57630309e89: reencrypt_answers start
ERROR    root:tasks.py:85 Reencryption ac92834c-b6ea-4f94-a77e-f57630309e89: cannot process applet 2cee7170-6474-4896-8d45-f7b4d56640be, skip
ERROR    root:tasks.py:86 ERROR
Traceback (most recent call last):
  File "/app/src/apps/users/tasks.py", line 67, in reencrypt_answers
    async with atomic(session):
               ~~~~~~^^^^^^^^^
  File "/app/src/apps/users/tasks.py", line 69, in reencrypt_answers
    count = await service.reencrypt_user_answers(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<8 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/unittest/mock.py", line 2321, in _execute_mock_call
    raise effect
Exception: ERROR
INFO     root:tasks.py:103 Reencryption ac92834c-b6ea-4f94-a77e-f57630309e89: schedule retry
INFO     root:tasks.py:25 Reencryption ac92834c-b6ea-4f94-a77e-f57630309e89: reencrypt_answers start
ERROR    root:tasks.py:85 Reencryption ac92834c-b6ea-4f94-a77e-f57630309e89: cannot process applet 2cee7170-6474-4896-8d45-f7b4d56640be, skip
ERROR    root:tasks.py:86 ERROR
Traceback (most recent call last):
  File "/app/src/apps/users/tasks.py", line 67, in reencrypt_answers
    async with atomic(session):
               ~~~~~~^^^^^^^^^
  File "/app/src/apps/users/tasks.py", line 69, in reencrypt_answers
    count = await service.reencrypt_user_answers(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<8 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/unittest/mock.py", line 2321, in _execute_mock_call
    raise effect
  File "/app/src/apps/users/tasks.py", line 67, in reencrypt_answers
    async with atomic(session):
               ~~~~~~^^^^^^^^^
  File "/app/src/apps/users/tasks.py", line 69, in reencrypt_answers
    count = await service.reencrypt_user_answers(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<8 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/unittest/mock.py", line 2321, in _execute_mock_call
    raise effect
Exception: ERROR