WARNING  api.access:structured_logs.py:183 {'http': {'url': 'http://test.com/invitations/private/00000000-0000-0000-0000-000000000000', 'request_path': '/invitations/private/00000000-0000-0000-0000-000000000000', 'status_code': 404, 'method': 'GET', 'request_id': '3ee6b846b3c94a30bb38a40f97c132aa', 'version': '1.1'}, 'network': {'client': {'ip': '127.0.0.1', 'port': 123}}, 'duration': 3899901, 'event': '127.0.0.1:123 - "GET http://test.com/invitations/private/00000000-0000-0000-0000-000000000000 HTTP/1.1" 404', 'request_id': '3ee6b846b3c94a30bb38a40f97c132aa', 'logger': 'api.access', 'level': 'warning', 'timestamp': '2025-03-31T19:10:36.332431Z'}